### PR TITLE
Added the `changes` parameter to the commit function

### PR DESCRIPTION
**Pull request by mssola**
Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>

### CODE REVIEW

**Comment by mssola** [comment]
Used in SUSE/zypper-docker#81.

**Comment by flavio** [comment]
Do we have to change the API version we target for that?

**Comment by mssola** [comment]
Apparently no. This works on my patch to zypper-docker. Maybe it wouldn't be a bad idea to raise the API version to 1.22 on another PR ?

**Comment by flavio** [comment]
Is there a reason to target this specific API version? I think we should target the lowest version of the API that provides the features we need.

**Comment by mssola** [comment]
I was saying 1.22 because it's the latest one iirc. Since 1.15 works, I think that we can keep using that.

**Comment by flavio** [comment]
Good

**Pull request merged**
